name: Documentation
description: Report an issue or improvement for the documentation.
title: "[Docs]: "
labels:
  - documentation
body:
  - type: textarea
    id: problem
    attributes:
      label: What's missing or incorrect?

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested improvement
